import React from 'react';
import { GeneratedResult, OutputFormat, AppLanguage, AIModel } from '../types';
import { TRANSLATIONS } from '../constants';
import { Copy, Check, Terminal, Code, FileText } from 'lucide-react';

interface ResultPanelProps {
  result: GeneratedResult | null;
  loading: boolean;
  onRegenerate: () => void;
  outputFormat: OutputFormat;
  setOutputFormat: (fmt: OutputFormat) => void;
  language: AppLanguage;
  model: AIModel;
}

export const ResultPanel: React.FC<ResultPanelProps> = ({ 
  result, loading, outputFormat, setOutputFormat, model 
}) => {
  const [copied, setCopied] = React.useState(false);

  const copyToClipboard = (text: string) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) return (
    <div className="h-full flex flex-col items-center justify-center p-12 space-y-4">
      <div className="w-12 h-12 border-4 border-orange-500/20 border-t-orange-500 rounded-full animate-spin"></div>
      <p className="text-zinc-500 text-xs tracking-widest uppercase animate-pulse">Compiling Director's Cut...</p>
    </div>
  );

  if (!result) return (
    <div className="h-full flex flex-col items-center justify-center p-12 text-zinc-400">
      <Terminal className="w-12 h-12 mb-4 opacity-10" />
      <p className="text-sm">Awaiting Generation</p>
    </div>
  );

  return (
    <div className="flex flex-col h-full animate-fade-in bg-white">
      <div className="flex items-center justify-between p-4 border-b border-zinc-100 bg-zinc-50">
        <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-orange-500"></div>
            <span className="text-xs font-bold text-zinc-600 uppercase tracking-widest">{model} PROMPT</span>
        </div>
        <div className="flex bg-zinc-200/50 rounded-lg p-1">
            {['normal', 'json', 'python'].map((fmt) => (
                <button 
                    key={fmt} 
                    onClick={() => setOutputFormat(fmt as OutputFormat)}
                    className={`px-3 py-1 text-[10px] uppercase font-bold rounded ${outputFormat === fmt ? 'bg-white shadow-sm text-zinc-800' : 'text-zinc-400 hover:text-zinc-600'}`}
                >
                    {fmt}
                </button>
            ))}
        </div>
      </div>

      <div className="flex-1 relative overflow-hidden bg-white">
         <div className="absolute inset-0 overflow-auto custom-scrollbar p-6">
            {outputFormat === 'json' ? (
                <pre className="text-xs font-mono text-emerald-600 whitespace-pre-wrap">{JSON.stringify(result.richData || { prompt: result.finalPrompt }, null, 2)}</pre>
            ) : outputFormat === 'python' ? (
                <pre className="text-xs font-mono text-blue-600 whitespace-pre-wrap">
{`import os
# Generated by Studio Space
# Target: ${model}

prompt = """${result.finalPrompt?.replace(/"/g, '\\"') || ''}"""

def generate():
    # SDK Implementation
    pass`}
                </pre>
            ) : (
                <p className="text-sm font-mono text-zinc-700 leading-loose whitespace-pre-wrap">{result.finalPrompt}</p>
            )}
         </div>
      </div>

      <div className="p-4 border-t border-zinc-100 bg-zinc-50 flex justify-end">
         <button onClick={() => copyToClipboard(result.finalPrompt || '')} className="flex items-center gap-2 px-4 py-2 bg-zinc-900 text-white rounded-lg text-xs font-bold hover:bg-zinc-800 transition-colors">
            {copied ? <Check className="w-4 h-4"/> : <Copy className="w-4 h-4"/>} {copied ? 'Copied' : 'Copy Code'}
         </button>
      </div>
    </div>
  );
};